application: flint-water-project
version: 1
runtime: php55
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /includes
  static_dir: includes

- url: /images
  static_dir: images
  
- url: /js
  static_dir: js
  
- url: /(.+\.php)$
  script: \1
  
- url: /(.*)
  static_files: index.php
  upload: index.php 